# file: site.yml
---
# password_hash requires the passlib python module to generate password hashes
# sudo pip install passlib

#------------------------------------------------------
# Make sure to export the AWS Keys `source env.sh`
#------------------------------------------------------
- name: Provision AWS Infrastucture using Terraform
  hosts: local_target
  roles:
    - aws.infra


- name: AWS | Install & Configure Instances
  remote_user: ec2-user
  hosts: nodes
  become: yes
  roles:
    - subscription_manager
    - ansible_ssh_pipelining
    - docker
    - atomic_scanner_plugins
    - container_check_stp
    - jq
    - skopeo
    - epel
    - cockpit
    - zsh
    - nodejs
    - wetty            # Not needed for Vagrant, use vagrant ssh
    # - LetsEncrypt    # Does not work with Vagrant, must be a public ip for Let'sEncrypt to work.
    # - sendgrid       # I send mail if you don't turn me off!
